version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=dev
    ports:
      - 3001:3001

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 3000:3000
    depends_on:
      - api
