version: '2'
services:
  api:
    image: node:8.9.4
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001
    command: bash -c "npm run api"

  ui:
    image: node:8.9.4
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: bash -c "npm start"
