version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001

  ui:
    build:
      context: ./
      dockerfile: ./docker/ui/Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
